language: go
deploy:
  provider: heroku
  buildpack: https://github.com/heroku/heroku-buildpack-go.git
  api_key:
    secure: "nIgeTilsgPQxEqKw4zMA+Jl0v7ET1isrqem8+Cu8oA2qSDAtVeR3GcpURY8WGx7GrXISIVtbbp42d1rHgvNStFSggYVVXbUqU9+Nor6hLSkByrmdGnir4oWTBznsdYzb4k0+vv7OmesUjwFOwNoHnb0LnZqB2L0bH0yvowg1fZ+A9Cy8uVNVJe8im/sYak4Pv0mH3WpOGGsP2MIWLIqRHXYCHJRwS6Dq6wgobm7iNNgxAU5Tuv3wKfa0rXzmXw2TkcxL9Y1pLzDlRse+PGxHKw0QZIOmrT/n8PZ5OFzmlUzaTnT92cdIOQIyybsdkcC2FkoaAVU6zHF1ZowP4lPU5bJGnQyuJ8OixoMriSVXshTgFJ2QqBm9VXmn/kbCQPDCiLTJywHwor9UBED3tqWGCVEjAgcLMn7jGQss6GDvROo1yJCrKaMUh5mmWk6g2tpvKDBGuE97/KbL3wkn9tOSPXFcXLz8/UmYOczQLmb8n9xiys5XOS4G3Qvk0tdPhyJhfUEu9hjGaBsC0zcvlFBv4VQTAvheaCerXJQ1hcSuB2tjIXU1ac7JfkAXFF9tZjRuCABMoMNKFrSjJErYg7Ttn3O3EgDwhcgg7IGtyuETR4yZgP59jH/sbWjfc5qf6hcrRJ9O48PVo/mdTigNrcZGc0BTJgX0cs/a6OZAatpXT5E="
  app: base-heroku-go-app
  on: master
